"""Local user configuration for contenido-bionico.

The repo ships source defaults, but setup writes user-specific choices under
`.bionico/`, which is ignored by git.
"""
from __future__ import annotations

import os
import tomllib
from pathlib import Path
from typing import Any


def _resolve_repo_root() -> Path:
    """Resolve the git checkout root, failing fast on unsupported installs.

    The package only works as an editable install from a git checkout (that is
    what bootstrap.sh / bootstrap.ps1 set up): runtime assets like
    package.json, node_modules and runs/ live next to pyproject.toml. In a
    non-editable install (e.g. a plain `pip install contenido-bionico` into
    site-packages) this path would silently point somewhere useless, so we
    raise a clear error instead.
    """
    root = Path(__file__).resolve().parents[3]
    if (root / "pyproject.toml").exists() and (root / "package.json").exists():
        return root
    raise RuntimeError(
        "contenido-bionico debe ejecutarse desde un checkout del repositorio "
        "instalado en modo editable. Clona el repositorio y corre bootstrap.sh "
        "(macOS/Linux) o bootstrap.ps1 (Windows) desde la carpeta del repo. "
        f"No encontre pyproject.toml y package.json junto al codigo en: {root}"
    )


REPO_ROOT = _resolve_repo_root()
LOCAL_DIR = REPO_ROOT / ".bionico"
CONFIG_PATH = LOCAL_DIR / "config.toml"
ENV_PATH = REPO_ROOT / ".env"
STYLE_REFERENCE_DIR = REPO_ROOT / "style_reference"


DEFAULTS: dict[str, Any] = {
    "setup_complete": False,
    "input_dir": "",
    "output_dir": "",
    "output_long_dir": "",
    "output_short_dir": "",
    "agent_engine": "subscription",
    "agent_provider": "claude_code",
    "transcription_provider": "elevenlabs",
}


def load_config() -> dict[str, Any]:
    data = DEFAULTS.copy()
    if CONFIG_PATH.exists():
        parsed = tomllib.loads(CONFIG_PATH.read_text(encoding="utf-8"))
        for key, value in parsed.items():
            if isinstance(value, (str, int, float, bool)):
                data[key] = value
    return data


def toml_quote(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def save_config(values: dict[str, Any]) -> None:
    LOCAL_DIR.mkdir(parents=True, exist_ok=True)
    merged = DEFAULTS.copy()
    merged.update(values)
    lines = [
        "# contenido-bionico local configuration",
        "# Generated by `contenido-bionico setup`. This file is ignored by git.",
        "",
    ]
    for key in DEFAULTS:
        lines.append(f"{key} = {toml_quote(merged[key])}")
    CONFIG_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _parse_env_line(line: str) -> tuple[str, str] | None:
    """Parse one .env line into (key, value), or None for non-assignments.

    Mirrors `shared.runtime.claude_runner.load_env` semantics: comment lines
    are skipped, an `export KEY=...` prefix is tolerated, surrounding quotes
    are stripped, and trailing inline comments are dropped on unquoted values.
    """
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    if stripped.startswith("export "):
        stripped = stripped[len("export "):].lstrip()
    if "=" not in stripped:
        return None
    key, value = stripped.split("=", 1)
    key = key.strip()
    if not key:
        return None
    value = value.strip()
    if len(value) >= 2 and (
        (value.startswith('"') and value.endswith('"'))
        or (value.startswith("'") and value.endswith("'"))
    ):
        value = value[1:-1]
    else:
        # Trailing inline comment (only meaningful on unquoted values).
        cut = min(
            (idx for idx in (value.find(" #"), value.find("\t#")) if idx != -1),
            default=-1,
        )
        if cut != -1:
            value = value[:cut].rstrip()
    return key, value


def read_env_file() -> dict[str, str]:
    values: dict[str, str] = {}
    for p in [ENV_PATH, REPO_ROOT.parent / ".env"]:
        if p.exists():
            for line in p.read_text(encoding="utf-8").splitlines():
                parsed = _parse_env_line(line)
                if parsed is not None:
                    values[parsed[0]] = parsed[1]
    return values



def write_env_values(updates: dict[str, str]) -> None:
    """Update managed keys in .env without touching the rest of the file.

    Comment lines and unrecognized lines are preserved verbatim; only lines
    assigning one of the updated keys are rewritten. New keys are appended.
    """
    pending = {k: v for k, v in updates.items() if v}
    existing_lines = (
        ENV_PATH.read_text(encoding="utf-8").splitlines() if ENV_PATH.exists() else None
    )
    out: list[str] = []
    seen: set[str] = set()
    if existing_lines is None:
        out = [
            "# contenido-bionico local secrets",
            "# Generated by `contenido-bionico setup`. This file is ignored by git.",
            "",
        ]
    else:
        for line in existing_lines:
            parsed = _parse_env_line(line)
            if parsed is not None and parsed[0] in pending:
                out.append(f"{parsed[0]}={pending[parsed[0]]}")
                seen.add(parsed[0])
            else:
                out.append(line)
    new_keys = sorted(key for key in pending if key not in seen)
    if new_keys and out and out[-1].strip():
        out.append("")
    for key in new_keys:
        out.append(f"{key}={pending[key]}")
    ENV_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")
    try:
        # Secrets file: owner read/write only (no-op/best effort on Windows).
        os.chmod(ENV_PATH, 0o600)
    except OSError:
        pass


def load_env_into_process() -> None:
    for key, value in read_env_file().items():
        os.environ.setdefault(key, value)


def configured_input_dir() -> Path | None:
    value = str(load_config().get("input_dir") or "").strip()
    return Path(value).expanduser() if value else None


def configured_output_dir(kind: str | None = None) -> Path | None:
    cfg = load_config()
    if kind in {"long", "short"}:
        value = str(cfg.get(f"output_{kind}_dir") or "").strip()
        if value:
            return Path(value).expanduser()
        legacy = str(cfg.get("output_dir") or "").strip()
        if legacy:
            return Path(legacy).expanduser() / kind
        # No config.toml (or an empty key): default next to the repo so the
        # pipeline writes output without any config present.
        return REPO_ROOT / f"output_{kind}"
    value = str(cfg.get("output_dir") or "").strip()
    if value:
        return Path(value).expanduser()
    return REPO_ROOT / "output"


def agent_provider() -> str:
    return str(load_config().get("agent_provider") or "claude_code")
