"""Codegen a Compositions TS module for the carousel (4:5 PNG slides).

The carousel is a single ``carousel`` composition whose frame count equals the
number of slides; each frame is rendered to its own PNG still. All slide content
is precomputed in Python and embedded as defaultProps, so the Remotion component
stays a dumb renderer.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# 4:5 portrait — the standard Instagram carousel size.
CAROUSEL_WIDTH = 1080
CAROUSEL_HEIGHT = 1350


class CarouselManifestError(RuntimeError):
    pass


def write_carousel_compositions_ts(*, slides: list[dict[str, Any]], out_path: Path) -> Path:
    """Write a Compositions TS module exposing the ``carousel`` composition.

    Args:
        slides: the ``CarouselSlide`` payloads (one per frame, hero first).
        out_path: destination .ts file (an isolated per-render path).

    Returns:
        Path to the generated .ts file.
    """
    if not slides:
        raise CarouselManifestError("carousel needs at least one slide")
    props_ts = json.dumps({"slides": slides}, ensure_ascii=False)
    body = (
        "// AUTO-GENERATED by Python orchestrator. DO NOT EDIT BY HAND.\n"
        'import type React from "react";\n'
        'import { Carousel } from "./Carousel";\n'
        'import type { CompositionEntry } from "./lib/types";\n'
        "\n"
        "export const COMPOSITIONS: ReadonlyArray<CompositionEntry & "
        "{ component: React.FC<any> }> = [\n"
        "  {\n"
        '    id: "carousel",\n'
        "    component: Carousel,\n"
        f"    durationInFrames: {len(slides)},\n"
        f"    width: {CAROUSEL_WIDTH},\n"
        f"    height: {CAROUSEL_HEIGHT},\n"
        f"    defaultProps: {props_ts},\n"
        "  },\n"
        "];\n"
    )
    out_path.write_text(body, encoding="utf-8")
    return out_path
