"""Codegen a Compositions TS module for a format composition, plus thin render
wrappers over the isolated-render entrypoints.

Mirrors `remotion_manifest_carousel.py` (the Compositions.<token>.ts body shape
and the isolated-entry contract `{ id, component, durationInFrames, width,
height, defaultProps }`) but is GENERIC: the component is chosen at call time
via `component_file` (e.g. "formats/TypingCarousel", no extension), so it uses a
DEFAULT import — every format component under `shared/remotion/src/formats/`
must `export default` its component. Props are embedded as defaultProps with
`ensure_ascii=False` so Spanish text stays literal in the generated TS.
"""
from __future__ import annotations

import json
from pathlib import Path

from contenido_bionico.shared.render_remotion import (
    render_isolated_composition,
    render_isolated_stills,
)


def write_format_composition_ts(
    comp_path: Path,
    *,
    composition_id: str,
    component_file: str,
    width: int,
    height: int,
    duration_frames: int,
    props: dict,
) -> None:
    """Write a Compositions TS module exposing ONE format composition.

    `component_file` is the src-relative path to the component without `.tsx`
    (e.g. "formats/TypingCarousel"); it is default-imported. The generated
    module exports `COMPOSITIONS` in the exact shape the isolated entrypoint
    template destructures.
    """
    props_ts = json.dumps(props, ensure_ascii=False)
    body = (
        "// AUTO-GENERATED by Python orchestrator. DO NOT EDIT BY HAND.\n"
        'import type React from "react";\n'
        f'import Comp from "./{component_file}";\n'
        "\n"
        "export const COMPOSITIONS: ReadonlyArray<{\n"
        "  id: string;\n"
        "  component: React.FC<any>;\n"
        "  durationInFrames: number;\n"
        "  width: number;\n"
        "  height: number;\n"
        "  defaultProps: Record<string, unknown>;\n"
        "}> = [\n"
        "  {\n"
        f'    id: "{composition_id}",\n'
        "    component: Comp,\n"
        f"    durationInFrames: {int(duration_frames)},\n"
        f"    width: {int(width)},\n"
        f"    height: {int(height)},\n"
        f"    defaultProps: {props_ts},\n"
        "  },\n"
        "];\n"
    )
    comp_path.write_text(body, encoding="utf-8")


def _write(composition_id, component_file, width, height, duration_frames, props):
    """Bind a `write_compositions(comp_path)` callback for the render helpers."""
    def _cb(comp_path: Path) -> None:
        write_format_composition_ts(
            comp_path,
            composition_id=composition_id,
            component_file=component_file,
            width=width,
            height=height,
            duration_frames=duration_frames,
            props=props,
        )
    return _cb


def render_format_video(
    *,
    composition_id: str,
    component_file: str,
    width: int,
    height: int,
    duration_frames: int,
    props: dict,
    out_mp4: Path,
) -> Path:
    """Render a full-frame opaque format comp to H.264 MP4 (`fast_opaque`)."""
    return render_isolated_composition(
        write_compositions=_write(
            composition_id, component_file, width, height, duration_frames, props
        ),
        composition_id=composition_id,
        out_webm=out_mp4,
        require_alpha=False,
        fast_opaque=True,
    )


def render_format_overlay(
    *,
    composition_id: str,
    component_file: str,
    width: int,
    height: int,
    duration_frames: int,
    props: dict,
    out_webm: Path,
) -> Path:
    """Render a transparent format overlay to VP9 WebM (alpha required)."""
    return render_isolated_composition(
        write_compositions=_write(
            composition_id, component_file, width, height, duration_frames, props
        ),
        composition_id=composition_id,
        out_webm=out_webm,
        require_alpha=True,
    )


def render_format_stills(
    *,
    composition_id: str,
    component_file: str,
    width: int,
    height: int,
    duration_frames: int,
    props: dict,
    out_pngs: list[Path],
    frames: list[int] | None = None,
) -> list[Path]:
    """Render one or more frames of a format comp to PNG stills."""
    return render_isolated_stills(
        write_compositions=_write(
            composition_id, component_file, width, height, duration_frames, props
        ),
        composition_id=composition_id,
        out_pngs=out_pngs,
        frames=frames,
    )
