"""Codegen a Compositions TS module for ONE quote post.

Each quote is rendered on its own: a single-frame `quote-post` composition whose
defaultProps carry that quote's text + fitted font size. The pipeline calls this
once per quote and renders it to a lossless PNG still.
"""
from __future__ import annotations

import json
from pathlib import Path

# Matches the 4:5 carousel/quote canvas.
QUOTE_WIDTH = 1080
QUOTE_HEIGHT = 1350


def write_quote_post_compositions_ts(*, text: str, font_px: int, out_path: Path) -> Path:
    """Write a Compositions TS module exposing the single-frame ``quote-post``.

    Args:
        text: the quote string.
        font_px: the body font size (fitted in Python, heuristic).
        out_path: destination .ts file (an isolated per-render path).
    """
    props_ts = json.dumps({"text": text, "fontPx": font_px}, ensure_ascii=False)
    body = (
        "// AUTO-GENERATED by Python orchestrator. DO NOT EDIT BY HAND.\n"
        'import type React from "react";\n'
        'import { QuotePost } from "./QuotePost";\n'
        'import type { CompositionEntry } from "./lib/types";\n'
        "\n"
        "export const COMPOSITIONS: ReadonlyArray<CompositionEntry & "
        "{ component: React.FC<any> }> = [\n"
        "  {\n"
        '    id: "quote-post",\n'
        "    component: QuotePost,\n"
        "    durationInFrames: 1,\n"
        f"    width: {QUOTE_WIDTH},\n"
        f"    height: {QUOTE_HEIGHT},\n"
        f"    defaultProps: {props_ts},\n"
        "  },\n"
        "];\n"
    )
    out_path.write_text(body, encoding="utf-8")
    return out_path
