// AUTO-GENERATED by Python orchestrator. DO NOT EDIT BY HAND.
import type React from "react";
import Comp from "./formats/CarouselMitos";

export const COMPOSITIONS: ReadonlyArray<{
  id: string;
  component: React.FC<any>;
  durationInFrames: number;
  width: number;
  height: number;
  defaultProps: Record<string, unknown>;
}> = [
  {
    id: "carousel-variant",
    component: Comp,
    durationInFrames: 7,
    width: 1080,
    height: 1350,
    defaultProps: {"title": "Un generador de contenido a prueba", "eyebrow": "Video de prueba", "slides": [{"kind": "par", "mito": "Para sacar varias piezas de un video tengo que editar cada una a mano desde cero.", "realidad": "Con una herramienta convierto un solo video en las distintas piezas que ya elegí de antemano.", "index": 1, "total": 5}, {"kind": "par", "mito": "Solo consigues el video recortado y nada más.", "realidad": "Saco clips subtitulados con gráficos, carruseles, pósters y contenido listo para compartir en redes.", "index": 2, "total": 5}, {"kind": "par", "mito": "Lo que te genera viene fijo y no puedes tocarlo.", "realidad": "Modifico subtítulos, cámara, animaciones, música, efectos de sonido y la calidad del video.", "index": 3, "total": 5}, {"kind": "par", "mito": "De un video solo sacas otro video.", "realidad": "Obtengo videos extra, videos carruseles, carruseles extra, imágenes, pósters y textos.", "index": 4, "total": 5}, {"kind": "par", "mito": "Prometen mucho pero con un video crudo real no funciona.", "realidad": "Voy a probar con un video raw como este si de verdad hace lo que promete.", "index": 5, "total": 5}, {"kind": "cta", "heading": "Sígueme para no perderte el resto", "body": "Rompemos otro mito cada semana.", "index": 0, "total": 0}], "palette": {"bg": "#1A1512", "ink": "#231D17", "paper": "#F6F1E7", "accent": "#F3A712", "accentSoft": "#F8D489"}},
  },
];
