ALTER TABLE jobs ADD COLUMN run_id TEXT;
ALTER TABLE jobs ADD COLUMN kind TEXT NOT NULL DEFAULT 'new';
ALTER TABLE jobs ADD COLUMN target TEXT;
ALTER TABLE jobs ADD COLUMN instructions TEXT;
ALTER TABLE jobs ADD COLUMN outputs TEXT;
